### ISSUE TITLE
spdk_nvme_ctrlr_cmd_io_raw_with_md() is available

### ISSUE THREAD

**Issue by youngtack** [OpenChannelSSD/liblightnvm#10]
Hi @safl,

spdk_nvme_ctrlr_cmd_io_raw_with_md() is available on SPDK master branch.
PPA write/read with meta data can work with this function.

Thanks,
@youngtack

**Comment by safl** [comment]
Hi @youngtack,

Thanks!

I've added it to the SPDK backend implementation on 'spdk.naive' branch. Note that the backend implementation is functional but does not perform. That is, commands go through the SPDK stack but performance is sub-par. Also, linking with SPDK is done statically and expects SPDK to be at "/opt/spdk".

Best,
@safl
