### ISSUE TITLE
some problems about building environment with QEMU

### ISSUE THREAD

**Issue by wuqiulin1995** [OpenChannelSSD/liblightnvm#12]
Hi

I'm building an initial environment with QEMU，but I don't know which branch of Linux kernel should I download. 

Thank you!
Qiulin.

**Comment by MatiasBjorling** [comment]
Hi Qiulin,

Use the latest 4.15 kernel. That has the latest work incorporated.

-Matias


Den 31. jan. 2018 08.21 skrev "wuqiulin1995" <notifications@github.com>:

**Comment by wuqiulin1995** [comment]
Is the for-4.15/pblk branch?

**Comment by MatiasBjorling** [comment]
You can install any 4.15 kernel. The for-4.15/pblk branch is already upstream (you can use it if you want).
