### ISSUE TITLE
some problems about using C API 

### ISSUE THREAD

**Issue by wuqiulin1995** [OpenChannelSSD/liblightnvm#13]
Hi 
I'm using the C API and I met some problems.

In the 
nvm_addr_write(struct nvm_dev * dev, struct nvm_addr addrs[], int naddrs, const void * buf, const void * meta, uint16_t flags, struct nvm_ret * ret)

function, addresses in the addrs[] are  interpreted as sector addresses, and the naddrs is the length of the addrs[], meta is the buffer containing metadata.

I think a page which contains four sectors, has an OOB, why the meta must be of size equal to device  naddrs * geo.meta_nbytes? 

Thanks.

**Comment by MatiasBjorling** [comment]
Hi Qiulin,

For each sector, there is a set of bytes in the OOB area. When issuing four, the metadata for all four data sectors must be filled. E.g., if the OOB area is 16 bytes per sector, then one has to supply a buffer of at least 64 bytes. 

@safl May this field be null? what will liblightnvm do in that case?

Thanks
