### ISSUE TITLE
liblightnvm ioctl command proble,

### ISSUE THREAD

**Issue by 425686558** [OpenChannelSSD/liblightnvm#2]
I read the liblightnvm code,in nvm_vblock.c file.
`int nvm_vblock_get(struct nvm_ioctl_vblock *vblock, struct nvm_tgt *tgt)
{
	int ret = 0;

	vblock->id = 0;
	vblock->bppa = 0;
	vblock->nppas = 0;
	vblock->ppa_bitmap = 0;
	vblock->vlun_id = 0;
	vblock->owner_id = 101;
	vblock->flags = NVM_PROV_RAND_LUN;

	ret = ioctl(tgt->fd, NVM_BLOCK_GET, vblock);

	NVM_DEBUG("ret(%d), vlun_id(%d), id(%llu), bppa(%llu)\n",
		  ret, vblock->vlun_id, vblock->id, vblock->bppa);

	return ret;
}`
I have a problem with the ioctl argument,"NVM_BLOCK_GET".

I also read the the newest kernel code,and can't find the "NVM_BLOCK_GET" argument.

**Comment by javigon** [comment]
Hi,

Kernel support for liblightnvm is not upstreamed yet. You can find a branch on the linux tree called liblnvm [1]. It follows liblightnvm development. Please note that it is under heavy refactoring at the moment.

[1] https://github.com/OpenChannelSSD/linux/tree/liblnvm

Javier.
