### ISSUE TITLE
Physical Address Extraction

### ISSUE THREAD

**Issue by goldshakil** [OpenChannelSSD/liblightnvm#31]
Hello there, 
I am new to OpenChannel SSDs and I had a question that I hope you can help me with.
I read the _lightnvm_ documentation and it's a little complicated to figure out how can I get the mapping between LBA to PBA.

I have several files which I have extracted their LBA through _fibmap_ API and now I want to see the mapping on the SSD in terms of the physical address.

I hope lightnvm is helpful to get the mapping  using _nvm_addr_. So can you help me out?

Thank you so much.

**Comment by birkelund** [comment]
Hi @goldshakil,

On an OpenChannel SSD there is really no difference. The LBA *is* the physical address.

If the address you have are OpenChannel addresses, then you can use `nvm_addr_dev2gen` to convert it into a "generic format" where you can easily extract the group, pu, chunk etc.
