### ISSUE TITLE
Does liblightnvm not support NVM_SPEC_VERID_12?

### ISSUE THREAD

**Issue by gnatseira** [OpenChannelSSD/liblightnvm#36]
I want to run liblightnvm on an open-channel SSD emulator with NVM_SPEC_VERID_12. However, I ran an example named `nvm_examples_vblk-ex01-ewr` and it returned invalid arugment. In function `nvm_be_ioctl_rprt()` it checks if the verid is NVM_SPEC_VERID_20. 
```C
if (NVM_SPEC_VERID_20 != dev->verid) {
	errno = EINVAL;
	return NULL;
}
```
So I want to ask whether liblightnvm supports NVM_SPEC_VERID_12. Or should I roll back to a specific commit that can support NVM_SPEC_VERID_12?
Looking forward to your reply, thank you!

**Comment by MatiasBjorling** [comment]
The OCSSD emulator is able to do 2.0 of the spec. What are you looking for in the 1.2 spec?

https://github.com/OpenChannelSSD/qemu-nvme

**Comment by gnatseira** [comment]
It seems that the emulator can not emulate multiple channels according to our test. Then I found FEMU developed by University of Chicago(https://github.com/ucare-uchicago/femu) support this feature. Unfortunately, FEMU only supports OpenChannel Specification 1.2 currently. So I think this problem can be solved by either liblightnvm with NVM_SPEC_VERID_12 or FEMU with NVM_SPEC_VERID_20.

**Comment by safl** [comment]
@gnatseira liblightnvm supports NVM_SPEC_VERID_12. However, the example code you refer to is specific to OCSSD 2.0 as it uses the helpers ``nvm_cmd_rprt_arbs/nvm_cmd_rprt`` which retrieves chunk-information via the 2.0 log-page. This is why you see the EINVAL error-code. If you would like to modify the example, then the equivalent command for OCSSD 1.2 is ``nvm_cmd_gbbt``.
However, path of least resistance would be to use QEMU version here: https://github.com/refenv/qemu on branch ``ocssd-again``, it supports emulating OCSSD 2.0 devices with multiple parallel units, which I think is what you want to experiment with?
Let me know if that works out for you :)

**Comment by MatiasBjorling** [comment]
@safl I think @gnatseira may be looking into the FEMU work that I did together with Huaicheng. That qemu work is able to simulate timings - but is limited to the 1.2 version.

**Comment by gnatseira** [comment]
> However, path of least resistance would be to use QEMU version here: https://github.com/refenv/qemu on branch `ocssd-again`, it supports emulating OCSSD 2.0 devices with multiple parallel units, which I think is what you want to experiment with?

Thank you for your reply. I will have a try and give you the feedback if I success.

**Comment by gnatseira** [comment]
> @safl I think @gnatseira may be looking into the FEMU work that I did together with Huaicheng. That qemu work is able to simulate timings - but is limited to the 1.2 version.



> @safl I think @gnatseira may be looking into the FEMU work that I did together with Huaicheng. That qemu work is able to simulate timings - but is limited to the 1.2 version.

@MatiasBjorling At first, I use your OCSSD emulator, but it can not emulate multiple channels. Then I found FEMU by accident. So I tried to use liblightnvm on FEMU and found this problem. I think the solution provided by @safl can be helpful. Thank you all very much!

**Comment by safl** [comment]
@gnatseira you are most welcome. Forgot to mention you can find documentation on the 'qemu-img' and 'qemu' parameters here:

https://github.com/refenv/qemu/blob/ocssd/hw/block/nvme/ocssd.c

**Comment by gnatseira** [comment]
@safl I used the branch `ocssd-again` of this reposity( https://github.com/refenv/qemu ) but failed to emulate a virtual ocssd. 
The first problem is that `qemu-img` can not identify `ocssd` type. The following instruction does not work. The error is "Unknown file format ocssd.img"
```shell
qemu-img create -f ocssd -o help
```
Then I found this page(https://github.com/refenv/qemu/blob/ocssd-again/hw/block/nvme/ocssd.c), which creates a raw file and relies on QEMU parameters to emulate ocssd. 
I create a raw file named `ocssd.img` by `qemu-img` and use the following instruction to launch QEMU.
```shell
sudo bin/qemu-system-x86_64 -m 4G -enable-kvm ubuntu.raw -drive=ocssd.img  \
-device nvme,serial=deadbeef,id=nvme0,num_grp=2,num_pu=4,num_chk=60,lbads=12
```
QEMU can not be launched and it indicates that ".num_grp not found".
So I'm wondering whether the QEMU version I use is the correct one or there are some wrong parameters.

**Comment by birkelund** [comment]
Hi @gnatseira,

The `num_grp`, `num_pu`, etc. options are on the new 'ocssd-ns' device.

So, something like this:

```
-drive file=<file>,if=none,id=<drive_id>
-device ocssd,serial=<serial>,id=nvme0
-device ocssd-ns,drive=<drive_id>,bus=nvme0,nsid=1,num_grp=2
```

**Comment by gnatseira** [comment]
@birkelund Thank you for your help. Now I am able to use the ocssd emulator and run examples successfully. 
@safl But I found an another problem. I created multiple threads to write to different channels. However, the time costed by multiple parallel writes are much larger than a write to a single channel.  In theory, channels are isolated to each other, thus the time shouldn't be much larger for parallel accesses. 
So I want to ask if ocssd emulator supports parallel IOs right now?  Or the program I wrote is incorrect？
Thank you so much!

**Comment by birkelund** [comment]
@gnatseira,

The I/O in QEMU is asynchronous. The concept of groups, parallel units and chunks are purely abstract, they just map to different lba ranges on the backing image. So, while you can have multiple I/Os outstanding to the backing image concurrently, I would not call it parallel. In any case you should not depend on QEMU for anything related to performance measuring. It’s a tool for testing correctness, not performance.

**Comment by gnatseira** [comment]
@birkelund I got it. Thank you all for your help. And I will close this issue.
