### ISSUE TITLE
How to get the block (OCSSD  v1.2) information?

### ISSUE THREAD

**Issue by ChaosD** [OpenChannelSSD/liblightnvm#39]
Hello, I'm new to lightnvm. Now I use **femu + lightnvm** to test my idea, however I don't know how to get the information of one block, especially the **block write pointer position**.
I read the document and some sourse code of Liblightnvm. But I only find *nvm_cmd_rprt* which is supported by OCSSD v2.0. Are there an alternative in OCSSD v1.2?
>struct nvm_spec_rprt_descr {
	uint8_t cs;		///< Chunk State (CS)
	uint8_t ct;		///< Chunk Type (CT)
	uint8_t wli;		///< Wear-level Index (WLI) 0-255
	uint8_t rsvd1[5];
	uint64_t addr;		///< AKA Starting LBA (SLBA)
	uint64_t naddrs;	///< AKA Number of blocks in chunk (CNLB)
	uint64_t wp;		///< Write Pointer (WP)
};

**Comment by safl** [comment]
On 1.2 the information comes from host-managed bad-block-table, have a look here:
http://lightnvm.io/liblightnvm/cli/nvm_bbt.html

And see the code for the tool for the API to use.

**Comment by ChaosD** [comment]
Tx! I don't release the bbt will manage the block information.

**Comment by ChaosD** [comment]
Sorry,  I still do not find the information about **write pointer**. There is only sample status(FREE, BAD, GBAD, ...) of the block.
Do you have any example code or more detailed document?
Thank you very much!

**Comment by safl** [comment]
Ah, in OCSSD 1.2, the write-pointer state is not immediately available as it is in OCSSD2.0 and in ZNS.

As I recall, one way of recovering the write-pointer state is to retrieve the BBT and for "Free" and "Host-Reserved blocks" send reads to the drive until reads fail. However, note that in OCSSD 1.2 it is the host responsibility to "manage" blocks and their state. E.g. the host tells the drive "I am using this block" via bbt-set(host-reserved) and host either recovers the WP by scanning or by persisting the state somewhere else.

**Comment by ChaosD** [comment]
Thanks~, the reply helps me a lot.

**Comment by safl** [comment]
You are welcome :)
