### ISSUE TITLE
some problems about building environment with hardware( CNEX open channel ssd )

### ISSUE THREAD

**Issue by RockyLim92** [OpenChannelSSD/liblightnvm#7]
HI,

I'm having difficulties for building an initial environment.

cuz I'm good student, I followed the direction of <http://openchannelssd.readthedocs.io/en/latest/gettingstarted/>

I have CNEX SSD board connected with my test PC using PCI interface.
At first, I install supported linux kernel version at <https://github.com/OpenChannelSSD/linux.git> and rebooted as the kernel. I checked the configurations too.

Next, I installed nvme-cli by typing 

~~~ sh
git clone https://github.com/linux-nvme/nvme-cli
cd nvme-cli
sudo make; sudo make install

sudo add-apt-repository ppa:sbates
sudo apt-get update
sudo apt-get install nvme-cli
~~~

and type 
~~~sh
sudo nvme lnvm list
~~~
but they exposed nothing

so I followed the direction like
~~~sh
sudo nvme lnvm init -d nvme0
sudo nvme lnvm list
~~~
but it was same

I don't know what's the problem and I wanna address this problem...

I check the /dev directory and they show like
~~~sh
heerak@LIM16:~$ ls /dev/nvme*
/dev/nvme0
~~~

please help me..

Thank you and cheers.
Rocky.

**Comment by RockyLim92** [comment]
Plus, nvme kernel module is built-in well

**Comment by MatiasBjorling** [comment]
Hi,

Could you try the pblk.cnex branch in the Linux repo. The firmware you have
requires a couple of extra patches.

Thanks,
Matias

Den 25. aug. 2017 12.09 skrev "RockyLim92" <notifications@github.com>:

**Comment by MatiasBjorling** [comment]
Rocky, did you get it to work?
