### ISSUE TITLE
Do you have tested your lightnvm library on Radian Memory Systems RMS-325?

### ISSUE THREAD

**Issue by cyb3727** [OpenChannelSSD/liblightnvm#8]
I have connected with CNEX Labs, and they say they don't have extra product CNEX Open Channel SSD to sell. I want to buy a  Radian Memory Systems RMS-325 instead. It is listed in lightnvm official website. So I want to confirm whether it is usefull under lightnvm. Thank you!

**Comment by MatiasBjorling** [comment]
Radien marks it as supported on their site. However, if you want it for academic purposes, you can also use the OpenSSD Cosmos+ platform. There is a FPGA implementation that supports open-channel. That might be easier to acquire.
